spring:
  application:
    name: catalog-service
  profiles:
    active: docker
  config:
    #import: optional:configserver:http://localhost:8888/docker
    import: optional:configserver:http://config-server:8888