version: '3.2'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    ports:
      - 9411:9411

  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    depends_on:
      - zipkin-service
      - mongodb
    ports:
      - 8761:8761

  config-server:
    build: config-service
    container_name: config-server
    depends_on:
      - eureka-service
    ports:
      - 8888:8888

  movie-service:
    build: movie-service
    restart: always
    container_name: movie-service
    depends_on:
      - config-server
    ports:
      - 8001:8001

  serie-service:
    build: serie-service
    restart: always
    container_name: serie-service
    depends_on:
      - config-server
    ports:
      - 8002:8002

  catalog-service:
    build: catalog-service
    restart: always
    container_name: catalog-service
    depends_on:
      - config-server
      - movie-service
      - serie-service
    ports:
      - 8003:8003

  api-gateway:
    build: api-gateway
    restart: always
    container_name: api-gateway
    depends_on:
      - catalog-service
    ports:
      - 8080:8080
