eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  zipkin:
    #base-url: http://localhost:9411/
    base-url: http://zipkin-service:9411/
  rabbitmq:
    username: guest
    password: guest
    #host: localhost
    host: rabbitmq-service
    port: 5672
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Rodrigo Brasil
  mail: rodrigo.sousabrasil@outlook.com
server:
  port: ${PORT:9999}
