server:
  port: 8001
  servlet:
    context-path: /movies/

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

queue:
  movie:
    name: movie-service

mensagem: hello world

management:
  endpoints:
    web:
      exposure:
        include: '*'
