server:
  port: 8002
  servlet:
    context-path: /series/

spring:
  data:
    mongodb:
      authentication-database: admin
      host: mongodb
      username: admin
      password: pass
      database: avaliacao2

queue:
  serie:
    name: serie-service 
